name: Cart Pricing CI

on:
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none
          ini-values: date.timezone=Europe/Paris

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Validate & Security
        run: | 
            composer validate --strict
            composer audit
        
      
      - name: Quality
        run: | 
            vendor/bin/phpcs
            vendor/bin/phpstan analyse src --level=6

      - name: Tests
        run: vendor/bin/phpunit
